#!/bin/sh
# File generated by ocamlbuild

cd /home/iskander/workspace/parajit/CQInterface

rm -f cinterface.o
rm -f cinterface.so
rm -f depsort.cmi
rm -f depsort.cmx
rm -f depsort.o
# Also clean the script itself
rm -f _build/sanitize.sh
